title: App Dashboard
subtitle: Home Server
documentTitle: Home
icon: fas fa-home

header: true
footer: false

columns: "3"
connectivityCheck: false

theme: default

links:
  - name: GitHub
    icon: fab fa-github
    url: https://github.com/joshuaconnor/
  - name: "Work Links"
    icon: "fas fa-file-alt"
    url: "#additional-page" 

services:
  - name: Media
    icon: fas fa-compact-disc
    items:
      - name: Plex
        subtitle: Media server
        logo: assets/logos/plex.png
        url: https://plex.joshaconnor.duckdns.org
      # - name: Radarr
      #   subtitle: Movies
      #   logo: assets/logos/radarr.png
      #   url: https://radarr.joshaconnor.duckdns.org
      - name: Sonarr
        subtitle: TV shows
        logo: assets/logos/sonarr.png
        url: https://sonarr.joshaconnor.duckdns.org
      # - name: Bazarr
      #   subtitle: Subtitles
      #   logo: assets/logos/bazarr.png
      # #   url: https://bazarr.joshaconnor.duckdns.org
      # - name: Jackett
      #   subtitle: Indexer aggregator
      #   logo: assets/logos/jackett.png
      #   url: https://jackett.joshaconnor.duckdns.org
      - name: Transmission
        subtitle: BitTorrent client
        logo: assets/logos/transmission.png
        url: https://transmission.joshaconnor.duckdns.org
      - name: Trilium
        subtitle: Knowledge Repository
        logo: assets/logos/trilium.png
        url: https://trilium.joshaconnor.duckdns.org
      # - name: Tautulli
      #   subtitle: Plex statistics
      #   logo: assets/logos/tautulli.png
      #   url: https://tautulli.joshaconnor.duckdns.org

  - name: Management
    icon: fas fa-tasks
    items:
      # - name: K8s Dashboard
      #   subtitle: Cluster configuration
      #   logo: assets/logos/kubernetes.png
      #   url: https://k8s.joshaconnor.duckdns.org
      - name: Traefik
        subtitle: Proxy configuration
        logo: assets/logos/traefik.png
        url: https://traefik.joshaconnor.duckdns.org
      # - name: DDNS Monitor
      #   subtitle: Domain management
      #   logo: assets/logos/ddns.svg
      #   url: https://ddns.joshaconnor.duckdns.org
      # - name: Pi-hole
      #   subtitle: DNS sinkhole
      #   logo: assets/logos/pihole.png
      #   url: https://pihole.joshaconnor.duckdns.org
      # - name: Synology DSM
      #   subtitle: NAS web UI
      #   logo: assets/logos/nas.png
      #   url: https://nas.joshaconnor.duckdns.org
      - name: OpenMediaVault
        subtitle: OMV web UI
        logo: assets/logos/omv.png
        url: https://omv.joshaconnor.duckdns.org
      # - name: Router
      #   subtitle: Router web UI
      #   logo: assets/logos/router.png
      #   url: https://router.joshaconnor.duckdns.org

  - name: More
    icon: fas fa-folder-open
    items:
      # - name: Home Assistant
      #   subtitle: Home automation
      #   logo: assets/logos/homeassistant.png
      #   url: https://home.joshaconnor.duckdns.org
      # - name: Grafana
      #   subtitle: Server monitoring
      #   logo: assets/logos/grafana.png
      #   url: https://grafana.joshaconnor.duckdns.org
      # - name: Prometheus
      #   subtitle: Server metrics
      #   logo: assets/logos/prometheus.png
      #   url: https://prometheus.joshaconnor.duckdns.org
      # - name: File Browser
      #   subtitle: File browser
      #   logo: assets/logos/filebrowser.png
      #   url: https://files.joshaconnor.duckdns.org
      # - name: Jitsi
      #   subtitle: Video conferencing
      #   logo: assets/logos/jitsi.png
      #   url: https://jitsi.joshaconnor.duckdns.org
