title: App Dashboard
subtitle: Home Server
documentTitle: Home
icon: fas fa-home

header: true
footer: false

columns: "3"
connectivityCheck: false

theme: default

links:
  - name: GitHub
    icon: fab fa-github
    url: https://github.com/joshuaconnor/
  - name: "Work Links"
    icon: "fas fa-file-alt"
    url: "https://connor-science.duckdns.org" 

services:
  - name: Favorites
    icon: fas fa-compact-disc
    items:
      - name: Gmail
        subtitle: eMail Service
        logo: assets/logos/gmail.png
        url: https://mail.google.com/mail/u/0/#inbox
      - name: Calendar
        subtitle: Digital Calendar
        logo: assets/logos/calendar.png
        url: https://calendar.google.com/calendar/u/0/r/week



  - name: Media
    icon: fas fa-compact-disc
    items:
      - name: Plex
        subtitle: Media server
        logo: assets/logos/plex.png
        url: https://plex.joshaconnor.duckdns.org
      - name: Calibre
        subtitle: eBook management server
        logo: assets/logos/calibre.png
        url: https://calibre.joshaconnor.duckdns.org
      - name: Trilium
        subtitle: Knowledge Repository
        logo: assets/logos/trilium.png
        url: https://trilium.joshaconnor.duckdns.org

  - name: Management
    icon: fas fa-tasks
    items:
      # - name: K8s Dashboard
      #   subtitle: Cluster configuration
      #   logo: assets/logos/kubernetes.png
      #   url: https://k8s.joshaconnor.duckdns.org
      - name: Traefik
        subtitle: Proxy configuration
        logo: assets/logos/traefik.png
        url: https://traefik.joshaconnor.duckdns.org
      # - name: DDNS Monitor
      #   subtitle: Domain management
      #   logo: assets/logos/ddns.svg
      #   url: https://ddns.joshaconnor.duckdns.org
      # - name: Pi-hole
      #   subtitle: DNS sinkhole
      #   logo: assets/logos/pihole.png
      #   url: https://pihole.joshaconnor.duckdns.org
      # - name: OpenMediaVault
      #   subtitle: OMV web UI
      #   logo: assets/logos/omv.png
      #   url: https://omv.joshaconnor.duckdns.org
      # - name: Home Assistant
      #   subtitle: Home automation
      #   logo: assets/logos/homeassistant.png
      #   url: https://home.joshaconnor.duckdns.org
      # - name: Grafana
      #   subtitle: Server monitoring
      #   logo: assets/logos/grafana.png
      #   url: https://grafana.joshaconnor.duckdns.org
      # - name: Prometheus
      #   subtitle: Server metrics
      #   logo: assets/logos/prometheus.png
      #   url: https://prometheus.joshaconnor.duckdns.org
      - name: File Browser
        subtitle: File browser
        logo: assets/logos/filebrowser.png
        url: https://files.joshaconnor.duckdns.org
      - name: Code Server
        subtitle: Code Editing
        logo: assets/logos/vscode.png
        url: https://code.joshaconnor.duckdns.org

  - name: Media Gathering
    icon: fas fa-folder-open
    items:
      - name: Radarr
        subtitle: Movies
        logo: assets/logos/radarr.png
        url: https://radarr.joshaconnor.duckdns.org
      - name: Sonarr
        subtitle: TV shows
        logo: assets/logos/sonarr.png
        url: https://sonarr.joshaconnor.duckdns.org
      # - name: Bazarr
      #   subtitle: Subtitles
      #   logo: assets/logos/bazarr.png
      # #   url: https://bazarr.joshaconnor.duckdns.org
      - name: Jackett
        subtitle: Indexer aggregator
        logo: assets/logos/jackett.png
        url: https://jackett.joshaconnor.duckdns.org
      - name: Transmission
        subtitle: BitTorrent client
        logo: assets/logos/transmission.png
        url: https://transmission.joshaconnor.duckdns.org

  - name: D&D
    icon: fas fa-dice-d20
    items:
      - name: 5e Tools
        subtitle: 5e Reference Tool
        logo: assets/logos/5e.png
        url: https://5e.tools/index.html
      - name: Homebrewry
        subtitle: 5e Document Generator
        logo: assets/logos/homebrewry.png
        url: https://homebrewery.naturalcrit.com/user/joshaconnor
      - name: Players Guide
        subtitle: Player Information
        logo: assets/logos/eyospg.png
        url: https://sites.google.com/view/eyosplayerguide/home
