apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minecraft
  name: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - env:
            - name: EULA
              value: "TRUE"
            - name: TYPE
              value: FABRIC
            - name: VERSION
              value: "1.18.1"
          image: itzg/minecraft-server:latest
          name: minecraft
          ports:
            - containerPort: 25565
              name: minecraft
          resources: {}
          volumeMounts:
            - mountPath: /data
              subPath: minecraft
              name: server
            - mountPath: /mods
              subPath: mods
              name: server
      restartPolicy: Always
      volumes:
        - name: server
          persistentVolumeClaim:
            claimName: server
status: {}
