---
    version: "2"
    services:
      filezilla:
        image: ghcr.io/linuxserver/filezilla
        container_name: filezilla
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Europe/London
        volumes:
          - /path/to/config:/config
        ports:
          - 3000:3000
        restart: unless-stopped