---
version: "2.1"
services:
  ubooquity:
    image: ghcr.io/linuxserver/ubooquity
    container_name: ubooquity
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - MAXMEM=<maxmem>
    volumes:
      - <path to data>:/config
      - <path to books>:/books
      - <path to comics>:/comics
      - <path to raw files>:/files
    ports:
      - 2202:2202
      - 2203:2203
    restart: unless-stopped