apiVersion: v1
kind: Service
metadata:
  name: mc-oneblock
spec:
  type: NodePort
  selector:
    app: mc-oneblock
  ports:
    - port: 25555
      targetPort: mc-oneblock
      nodePort: 25555
      name: mc-oneblock