apiVersion: v1
kind: Service
metadata:
  name: mc-oneblock
spec:
  type: NodePort
  selector:
    app: mc-oneblock
  ports:
    - port: 25566
      targetPort: 25565
      name: mc-oneblock
      nodePort: 25566
