namespace: server
resources:
  - ingress.yaml
  - middleware.yaml
#  - namespace.yaml
#  - sealed-secret.yaml
  - secrets.yaml
  - service.yaml
commonLabels:
  app: traefik
configMapGenerator:
  - name: traefik-forward-auth
    files:
      - traefik-forward-auth.ini
helmChartInflationGenerator:
  - chartName: traefik
    chartVersion: v9.18.0
    chartRepoUrl: https://helm.traefik.io/traefik
    releaseName: traefik
    releaseNamespace: server
    values: values.yaml
