apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth
spec:
  forwardAuth:
    address: http://traefik-internal:4181
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-User
      - X-Secret