apiVersion: v1
kind: PersistentVolume
metadata:
  name: server
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /serverdata/server
  claimRef: 
    namespace: default
    name: server
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 6Ti
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /serverdata/media
  claimRef:
    namespace: default
    name: media
  persistentVolumeReclaimPolicy: Retain
