apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server
  namespace: server
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: server
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Ti
  volumeName: media
---
# Source: portainer/templates/pvc.yaml
# kind: "PersistentVolumeClaim"
# apiVersion: "v1"
# metadata:
#   name: portainer
#   namespace: portainer  
#   annotations:
#     volume.alpha.kubernetes.io/storage-class: "generic"
#   labels:
#     io.portainer.kubernetes.application.stack: portainer
#     app.kubernetes.io/name: portainer
#     app.kubernetes.io/instance: portainer
#     app.kubernetes.io/version: "ce-latest-ee-2.0.2"
# spec:
#   accessModes:
#     - "ReadWriteOnce"
#   resources:
#     requests:
#       storage: "10Gi"
