apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server
  namespace: server
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: server
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Ti
  volumeName: media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code
  namespace: server
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: code
