apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: transmission
  namespace: server
spec:
  encryptedData:
    OPENVPN_PASSWORD: AgBAbSm1fkzhxI1JUgS11H4TQud0FPSpTgNZ377TDjA1d82Gh0beOWT9OmoSTtSxkvl3ZT7iCHz5i74biEjghEt1UuTyZ6erIRV+S9ZkBFZRAeRnaVzV0RPhPrHvzCWlF/YL2mH7H1+VuYor2ngEBqmnoSHL3TYZjd36Y/3kkB5Z75ssvHG6Yn8KyKhQpQvE482IZXFVucW4cGsrd7jHrWTI/c4JKTRdFh7C/LayUrM+XdiwN9wS1EXmVhF6b+ArWxYafx6trW68XFKFeKfvg8M8URCCzAfvYw5JLtIeNWW5yLv/njuFMs6Iz3jhKbyGip2hJxaGJVKQVn1Dv82uGZd0rNEH2uIsrRxS8QvWm+WAsnTpFijL8GeRHBKw6YSZrZkB+IFiEefzxLpFs6ZtbXsa7IDalMDEMuTtzIyppvmbGgaPf9c7seQFYnMd6N1+f9Fk66SmXMhsvIg4jba4iOMaL2xyNetMKzLA0JBILc7zguH0ePSW9ZOQQ1JTBStZUx+K2CT4Wa8Z3ohcOdOKP2JAGOJT949eQv5kzNX0AgEvhdz6jP3gJG8Fnti7rachsQ3k5DOiPbjls0sbxNgqRmBI7TbqST910N6TvpvX9+INXhetfv/uC4u5wufcotoyVUgq2RvbzQXBa20PMdkuLx2VCfndbiNaaV/+XIPuJpGtcAs8+oDC4xee/5u7t/yZrrcPIOlUcd+E5atPhYqPdRCNuMXTuV/+eW0=
    OPENVPN_USERNAME: AgBbH9r2cvf7npsTV1waxNbZcaKDwlBnsKj2lBoVqSlsVD3NI4lSFyiAERgUTB1Jmgf9VUJl0G2zwD4h0QgU6YZ4I6+k2FaD2bJjdfnFr8kz5AUvqm+CGr2L00TMCZGss/IRpnkDWbNLg/sIWgggroW/6SRee1/0dsirlOTVsUtHBkd1Pn/dq3uWdA0IohitoE26nj/+/lVOJqMCTAKfdbLbvMmhx9BQ/TaZh58zhe/I6MtaJnINjwICNkEteCNCRBBkjCxERQ9+4IVIotnRkPOdNv3u6RDoyZ7F9trNRpVYu90XeAKL/KEDMmoLjjYprhl6cpJ8fSLhhrxdL4aWqu6KjgQl+6488LPllQwJolKyIbkiIxXd+jvLeiin0/bJSDIi70S0wYzUIQKGxO9Qlb/L8A3Z+waQwoIPbLS1D2u2nv4swkhIPmw/m6nl77PmwLeDLhs8VVdHZWI8LBAvKIDT821ixNkymnvjP5bSMp1VySwX07bwMyofk+yEEIb8xd8+xF5kOnGM/yBqBZRexFrGLQVQjrqQxXAM/8DSjEuZXjhyAxN77D+HyUGLlk6FCZyYJP+dB0sSD22kt2DAFmAcSn4VYT/9YWF6mbYXLnich7neahn+2ic/GFhWhzKLFkBqnG+3bS+w5YYDqtWBxseRYxgsWllHe3aMXVLhF/JnjmNnbEH10kJ5sMa/CeP9avV4sT90wSA8yGvMj6aHH+3HzCJaUFo2mng=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: transmission
      namespace: server
    type: Opaque

