title: J. Connor
subtitle: "The Fletcher Academy"
documentTitle: Home
icon: fas fa-home

header: true
footer: false

columns: "3"
connectivityCheck: false

# message:
#   # url: "https://<my-api-endpoint>" # Can fetch information from an endpoint to override value below.
#   # mapping: # allows to map fields from the remote format to the one expected by Homer
#   #   title: 'id' # use value from field 'id' as title
#   #   content: 'value' # value from field 'value' as content
#   # refreshInterval: 10000 # Optional: time interval to refresh message
#   #
#   # Real example using chucknorris.io for showing Chuck Norris facts as messages:
#   # url: https://api.chucknorris.io/jokes/random
#   # mapping:
#   #   title: 'id'
#   #   content: 'value'
#   # refreshInterval: 10000
#   style: "is-info"
#   title: "Consider Adding"
#   content: "https://www.pivotinteractives.com/, https://www.gimkit.com/, https://quizlet.com/latest, https://www.classmarker.com/"

theme: default

colors:
  light:
    highlight-primary: "#78797D"
    highlight-secondary: "#77202D"
    highlight-hover: "#AA5360"
    background: "#CFCFCF"
    card-background: "#E8E8E8"
    text: "#1D1D1D"
    text-header: "#E8E8E8"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.3)
    link-hover: "#363636"
    # background-image: "assets/your/light/bg.png"
  dark:
    highlight-primary: "#5E0714"
    highlight-secondary: "#77202D"
    highlight-hover: "#929397"
    background: "#78797D"
    card-background: "#929397"
    text: "#202020"
    text-header: "#ffffff"
    text-title: "#202020"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.5)
    link-hover: "#363636"
    # background-image: "assets/your/dark/bg.png"

links:   
  - name: "Daily Morning"
    icon: "fas fa-file-alt"
    url: "/assets/links/links1.html"

services:
  - name: "Daily Apps"
    icon: "fas fa-envelope"
    items:
      - name: "Gmail"
        logo: "assets/logos/gmail.png"
        subtitle: "eMail"
        tag: "app"
        url: "https://mail.google.com/mail/u/0/#inbox"
      - name: "Google Drive"
        logo: "assets/logos/drive.png"
        subtitle: "Cloud Storage"
        tag: "app"
        url: "https://drive.google.com/drive/my-drive"
      - name: "Google Classroom"
        logo: "assets/logos/classroom.png"
        subtitle: "Homework Management"
        tag: "app"
        url: "https://classroom.google.com/h"
  - name: "Management"
    icon: "fas fa-tasks"
    items:
      - name: "Go Guardian"
        logo: "assets/logos/goguardian.png"
        subtitle: "Chromebook Activity Management"
        tag: "app"
        url: "https://teacher.goguardian.com/classrooms/active"
      - name: "Renweb"
        logo: "assets/logos/renweb.png"
        subtitle: "Student Record Managment"
        tag: "app"
        url: "https://renweb1.renweb.com/renweb1/#/Home"
      - name: "Checks - All"
        logo: "assets/logos/checks.png"
        subtitle: "Daily Student Record"
        tag: "app"
        url: "https://docs.google.com/spreadsheets/d/153zyLGUPmfzQDs4uR75cpSD_emj_1YvKT4HkHMgQK_g/edit"
  - name: "Resources"
    icon: "fas fa-cloud"
    items:
      - name: "TPT School Access"
        logo: "assets/logos/tpt.png"
        subtitle: "Worksheet Resource"
        tag: "app"
        url: https://www.tptschoolaccess.com/
      - name: "Calendar"
        logo: "assets/logos/calendar.png"
        subtitle: "Scheduling Resource"
        tag: "app"
        url: https://calendar.google.com/
      - name: "Students File"
        logo: "assets/logos/files.png"
        subtitle: "Student Records"
        tag: "app"
        url: "https://docs.google.com/spreadsheets/d/1D5Qj20H_vi8KJ2mfgiRFtnI-JNFkhISkOwHxBUruR4g/edit"
  - name: "Monday"
    icon: "fas fa-calendar-day"
    items:
      - name: "Scholastic: Science World"
        logo: "assets/logos/scienceworld.png"
        subtitle: "Science Article Homework"
        tag: "app"
        url: https://digital.scholastic.com/#/products?app=scienceworld
      - name: "ck12"
        logo: "assets/logos/ck12.png"
        subtitle: "Digital Textbook"
        tag: "app"
        url: "https://www.ck12.org/teacher/"
      - name: "Books"
        logo: "assets/logos/calibre.png"
        subtitle: "The Martian"
        tag: "app"
        url: "https://books.connor-science.duckdns.org"
  - name: "Tuesday"
    icon: "fas fa-calendar-day"
    items:
      - name: "edPuzzle"
        logo: "assets/logos/edpuzzle.png"
        subtitle: "Video Based Homework"
        tag: "app"
        url: "https://edpuzzle.com/content"
      - name: "Flipgrid"
        logo: "assets/logos/flipgrid.png"
        subtitle: "Video Discussion Homework"
        tag: "app"
        url: https://admin.flipgrid.com/manage/dashboard
  - name: "Wednesday"
    icon: "fas fa-calendar-day"
    items:
      - name: "Google Jamboard"
        logo: "assets/logos/jamboard.png"
        subtitle: "Interactive Whiteboard"
        tag: "app"
        url: https://jamboard.google.com/
      - name: "Padlet"
        logo: "assets/logos/padlet.png"
        subtitle: "Visual Orginzation Homework"
        tag: "app"
        url: https://padlet.com/dashboard
  - name: "Thursday"
    icon: "fas fa-calendar-day"
    items:
      - name: "Quizlet"
        logo: "assets/logos/quizlet.png"
        subtitle: "Flashcards"
        tag: "app"
        url: https://quizlet.com/latest
      - name: "GimKit"
        logo: "assets/logos/gimkit.png"
        subtitle: "Gamified Homework"
        tag: "app"
        url: https://www.gimkit.com/
      - name: "Kahoot!"
        logo: "assets/logos/kahoot.png"
        subtitle: "Games Homework"
        tag: "app"
        url: https://create.kahoot.it/
  - name: "Friday"
    icon: "fas fa-calendar-day"
    items:
      - name: "Classmarker"
        logo: "assets/logos/classmarker.png"
        subtitle: "Testing"
        tag: "app"
        url: https://www.classmarker.com/
      - name: "Pivot Interactive"
        logo: "assets/logos/pivot.png"
        subtitle: "Interactive Digital Labs"
        tag: "app"
        url: https://www.pivotinteractives.com/
